// <auto-generated />
namespace Labsheet31March.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRestaurantData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRestaurantData));
        
        string IMigrationMetadata.Id
        {
            get { return "202503311031522_AddRestaurantData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
